---
- name: Download
  hosts: all
  become: yes
  vars:
    tf_binary: https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
    download_files:
      - https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
      - https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
    tmp_dir: /opt/tmp
    bin_dir: /usr/local/bin

  tasks:
    - name: Create /opt/tmp
      file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: 0755

    - name: Download Files using get_url
      get_url:
        url: "{{ item }}"
        dest: "{{ tmp_dir }}"
      loop: "{{ download_files }}"

    - name: Unpack All Files to Dest
      unarchive:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: true
      loop:
        - {
            "src": "{{ tmp_dir }}/terraform_1.0.7_linux_amd64.zip",
            "dest": "{{ bin_dir }}",
          }
        - {
            "src": "{{ tmp_dir }}/packer_1.7.5_linux_amd64.zip",
            "dest": "{{ bin_dir }}",
          }
