---
- name: Download
  hosts: all
  become: yes
  vars:
    tf_binary: https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
    download_files:
      - https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
      - https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
  tasks:
    - name: Download Files using get_url
      get_url:
        url: "{{ item }}"
        dest: "/opt/tmp"
      with_items: "{{ download_files }}"
    - name: Unpack All Files to Dest
      unarchive: src="{{ item.src }}"
        dest="{{ item.dest }}"
        remote_src=yes
      loop:
        - {
            "src": "/opt/tmp/terraform_1.0.7_linux_amd64.zip",
            "dest": "/usr/local/bin",
          }
        - {
            "src": "/opt/tmp/packer_1.7.5_linux_amd64.zip",
            "dest": "/usr/local/bin",
          }
